zookeeper:
  image: julywind/zookeeper
  ports: 
    - "49181:2181"
    - "22"
nimbus:
  image: julywind/storm-nimbus:2.2.0
  ports:
    - "49773:3773"
    - "49772:3772"
    - "49627:6627"
    - "22"
  links: 
    - zookeeper:zk
supervisor:
  image: julywind/storm-supervisor:2.2.0
  ports:
    - "8000"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
ui:
  image: julywind/storm-ui:2.2.0
  ports:
    - "49080:8080"
    - "22"
  links: 
    - nimbus:nimbus
    - zookeeper:zk
